Boxfile         = { Instruction } ;
Instruction     = FROM
                | ENV 
                | WORKDIR
                | USER 
                | LABEL 
                | FETCH
                | COPY
                | INSTALL
                | SETUP
                | SCAN
                | EXPOSE 
                | HEALTHCHECK
                | STOPSIGNAL
                | ENTRYPOINT
                | CMD
                | comment 
                | emptyline ;

letter         = "A"..."Z" | "a"..."z" ;
digit          = "0"..."9" ;
symbol         = "[" | "]" | "{" | "}" | "(" | ")" | "<" | ">"
                | "'" | '"' | "=" | "|" | "." | "," | ";" | "-" 
                | "+" | "*" | "?" | "!" | "@" | "#" | "$" | "%"
                | "^" | "&" | "_" | "~" | "`" | "/" | "\" | "\n"
                | "\t" | "\r" | "\f" | "\b" ;

whitespace     = " " | "\t" ;
newline        = "\n" | "\r\n" ;
comment        = "#", { ( letter | symbol ) }, { newline };