name: rust_box ci
run-name: Rust CI launched by @${{ github.actor }}

on: [push, pull_request]

jobs:

  check:
    name: cargo check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
      - name: cargo check
        uses: actions-rs/cargo@v1 
        with:
          command: check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -W clippy::pedantic

